### ISSUE TITLE
Hello, can you add Udp2raw-tunnel support or something similar? thank you

### ISSUE THREAD

**Issue by qnyblog** [Zackptg5/Wireguard-Pi-Hole-Cloudflared-Unbound-DNSCrypt-VPN-Server#8]
Hello, can you add Udp2raw-tunnel support or something similar? thank you
ISP providers in some countries add QoS restriction, if use Udp2raw-tunnel can helps Bypass UDP masking or QoS restrictions

**Comment by Zackptg5** [comment]
Since it's not something I'd ever use and it's not officially supported, probably not. Reasons for wireguard not support TCP officially are listed on the [page here](https://www.wireguard.com/known-limitations/)..
UDP2raw-tunnel doesn't officially support wireguard itself either although it may work.
UDPtunnel looks like it's an easy setup though, just run a single command: https://gist.github.com/insdavm/90cbeffe76ba4a51251d83af604adf94
